include(":base")
include(":command")
include(":common")
include(":concurrent")
include(":csv")
include(":file")
include(":generate")
include(":http")
include(":jar")
include(":json")
include(":jvm")
include(":jxl")
include(":logging")
include(":resource")
include(":state")
include(":upload")
include(":math")
include(":validator")
include(":reflect")
include(":jwt")

//libraries
apply(from = "${rootDir}/libraries/libraries.gradle")